require "BBB/pins/io/pin_mapper"
require "BBB/pins/io/mapped"
require "BBB/pins/io/cape"
require "BBB/pins/io/ain"
require "BBB/pins/io/gpio"
require "BBB/pins/io/pwm"
require "BBB/pins/io/i2c"

require "BBB/pins/pinnable"
require "BBB/pins/digital_pin"
require "BBB/pins/analog_pin"
require "BBB/pins/pwm_pin"
require "BBB/pins/i2c"
